### ISSUE TITLE
pytorch environment？

### ISSUE THREAD

**Issue by qinyouyou** [JinYize/self2self_pytorch#1]
Hello，Can you give some configuration information？Thank you very much！

**Comment by JinYize** [comment]
My configuration is:
- GPU: 3060
- Python version: 3.7.6
- torch+cuda version: 1.9.0+cu111

**Comment by qinyouyou** [comment]
Thank you very much！ Through experiments, I found that the image size must be a multiple of 32, which is related to downsampling in the coding stage. How to deal with other sizes? For example, for 400 * 400 images, the amount of calculation will increase a lot if filled. Thank you.

**Comment by JinYize** [comment]
Hi qinyouyou, to deal with other sizes, maybe you could try cropping or padding the input images. I will update this repo to support other sizes soon.
